export const PRODUCT_CART_LIST_REQUEST = "PRODUCT_CART_LIST_REQUEST";
export const PRODUCT_CART_LIST_SUCCESS = "PRODUCT_CART_LIST_SUCCESS";
export const PRODUCT_CART_LIST_FAIL = "PRODUCT_CART_LIST_FAIL";

export const CART_LIST_REQUEST = "CART_LIST_REQUEST";
export const CART_LIST_SUCCESS = "CART_LIST_SUCCESS";
export const CART_LIST_FAIL = "CART_LIST_FAIL";

export const CART_CREATE_REQUEST = "CART_CREATE_REQUEST";
export const CART_CREATE_SUCCESS = "CART_CREATE_SUCCESS";
export const CART_CREATE_FAIL = "CART_CREATE_FAIL";

export const CART_UPDATE_REQUEST = "CART_UPDATE_REQUEST";
export const CART_UPDATE_SUCCESS = "CART_UPDATE_SUCCESS";
export const CART_UPDATE_FAIL = "CART_UPDATE_FAIL";

export const CART_DELETE_REQUEST = "CART_DELETE_REQUEST";
export const CART_DELETE_SUCCESS = "CART_DELETE_SUCCESS";
export const CART_DELETE_FAIL = "CART_DELETE_FAIL";

export const ALL_CART_DELETE_REQUEST = "ALL_CART_DELETE_REQUEST";
export const ALL_CART_DELETE_SUCCESS = "ALL_CART_DELETE_SUCCESS";
export const ALL_CART_DELETE_FAIL = "ALL_CART_DELETE_FAIL";
