export const DRIVER_LOGIN_REQUEST = "DRIVER_LOGIN_REQUEST";
export const DRIVER_LOGIN_SUCCESS = "DRIVER_LOGIN_SUCCESS";
export const DRIVER_LOGIN_FAIL = "DRIVER_LOGIN_FAIL";
export const DRIVER_LOGOUT = "DRIVER_LOGOUT";

export const DRIVER_REGISTER_REQUEST = "DRIVER_REGISTER_REQUEST";
export const DRIVER_REGISTER_SUCCESS = "DRIVER_REGISTER_SUCCESS";
export const DRIVER_REGISTER_FAIL = "DRIVER_REGISTER_FAIL";

export const DRIVER_UPDATE_STATUS_REQUEST = "DRIVER_UPDATE_STATUS_REQUEST";
export const DRIVER_UPDATE_STATUS_SUCCESS = "DRIVER_UPDATE_STATUS_SUCCESS";
export const DRIVER_UPDATE_STATUS_FAIL = "DRIVER_UPDATE_STATUS_FAIL";

export const DRIVER_UPDATE_LOCATION_REQUEST = "DRIVER_UPDATE_LOCATION_REQUEST";
export const DRIVER_UPDATE_LOCATION_SUCCESS = "DRIVER_UPDATE_LOCATION_SUCCESS";
export const DRIVER_UPDATE_LOCATION_FAIL = "DRIVER_UPDATE_LOCATION_FAIL";
