// export const REVIEW_ADMIN_CONFIRM_LIST_REQUEST = "REVIEW_ADMIN_CONFIRM_LIST_REQUES";
// export const REVIEW_ADMIN_CONFIRM_LIST_SUCCESS = "REVIEW_ADMIN_CONFIRM_LIST_LIST_SUCCESS";
// export const REVIEW_ADMIN_CONFIRM_LIST_FAIL ="REVIEW_ADMIN_CONFIRM_LIST_FAIL";

// export const REVIEW_ADMIN_CONFIRM_UPDATE_REQUEST ="REVIEW_ADMIN_CONFIRM_UPDATE_REQUEST";
// export const REVIEW_ADMIN_CONFIRM_UPDATE_SUCCESS ="REVIEW_ADMIN_CONFIRM_UPDATE_SUCCESS";
// export const REVIEW_ADMIN_CONFIRM_UPDATE_FAIL = "REVIEW_ADMIN_CONFIRM_UPDATE_FAIL";

// export const REVIEW_CUSTOMER_DELETE_REQUEST = "REVIEW_CUSTOMER_DELETE_REQUEST";
// export const REVIEW_CUSTOMER_DELETE_SUCCESS = "REVIEW_CUSTOMER_DELETE_SUCCESS";
// export const REVIEW_CUSTOMER_DELETE_FAIL = "REVIEW_CUSTOMER_DELETE_FAIL";

export const REVIEW_CUSTOMER_LIST_REQUEST = "REVIEW_CUSTOMER_LIST_REQUEST";
export const REVIEW_CUSTOMER_LIST_SUCCESS = "REVIEW_CUSTOMER_LIST_SUCCESS";
export const REVIEW_CUSTOMER_LIST_FAIL = "REVIEW_CUSTOMER_LIST_FAIL";

export const REVIEW_CUSTOMER_CREATE_REQUEST = "REVIEW_CUSTOMER_CREATE_REQUEST";
export const REVIEW_CUSTOMER_CREATE_SUCCESS = "REVIEW_CUSTOMER_CREATE_SUCCESS";
export const REVIEW_CUSTOMER_CREATE_FAIL = "REVIEW_CUSTOMER_CREATE_FAIL";
