export const DELIVERY_LIST_FOR_ADMIN_REQUEST = "DELIVERY_LIST_FOR_ADMIN_REQUEST";
export const DELIVERY_LIST_FOR_ADMIN_SUCCESS = "DELIVERY_LIST_FOR_ADMIN_SUCCESS";
export const DELIVERY_LIST_FOR_ADMIN_FAIL = "DELIVERY_LIST_FOR_ADMIN_FAIL";

export const DELIVERY_LIST_FOR_CUSTOMER_REQUEST = "DELIVERY_LIST_FOR_CUSTOMER_REQUEST";
export const DELIVERY_LIST_FOR_CUSTOMER_SUCCESS = "DELIVERY_LIST_FOR_CUSTOMER_SUCCESS";
export const DELIVERY_LIST_FOR_CUSTOMER_FAIL = "DELIVERY_LIST_FOR_CUSTOMER_FAIL";

export const CREATE_DELIVERY_REQUEST = "CREATE_DELIVERY_REQUEST";
export const CREATE_DELIVERY_SUCCESS = "CREATE_DELIVERY_SUCCESS";
export const CREATE_DELIVERY_FAIL = "CREATE_DELIVERY_FAIL";

export const UPDATE_DELIVERY_REQUEST = "UPDATE_DELIVERY_REQUEST";
export const UPDATE_DELIVERY_SUCCESS = "UPDATE_DELIVERY_SUCCESS";
export const UPDATE_DELIVERY_FAIL = "UPDATE_DELIVERY_FAIL";

export const DELIVERY_VIEW_BY_ID_REQUEST = "DELIVERY_VIEW_BY_ID_REQUEST";
export const DELIVERY_VIEW_BY_ID_SUCCESS = "DELIVERY_VIEW_BY_ID_SUCCESS";
export const DELIVERY_VIEW_BY_ID_FAIL = "DELIVERY_VIEW_BY_ID_FAIL";

export const DELIVERY_UPDATE_BY_ID_REQUEST = "DELIVERY_UPDATE_BY_ID_REQUEST";
export const DELIVERY_UPDATE_BY_ID_SUCCESS = "DELIVERY_UPDATE_BY_ID_SUCCESS";
export const DELIVERY_UPDATE_BY_ID_FAIL = "DELIVERY_UPDATE_BY_ID_FAIL";
