export const PRODUCTS_LIST_FOR_VENDOR_REQUEST = "PRODUCTS_LIST_FOR_VENDOR_REQUEST";
export const PRODUCTS_LIST_FOR_VENDOR_SUCCESS = "PRODUCTS_LIST_FOR_VENDOR_SUCCESS";
export const PRODUCTS_LIST_FOR_VENDOR_FAIL = "PRODUCTS_LIST_FOR_VENDOR_FAIL";

export const PRODUCTS_LIST_FOR_CUSTOMER_REQUEST = "PRODUCTS_LIST_FOR_CUSTOMER_REQUEST";
export const PRODUCTS_LIST_FOR_CUSTOMER_SUCCESS = "PRODUCTS_LIST_FOR_CUSTOMER_SUCCESS";
export const PRODUCTS_LIST_FOR_CUSTOMER_FAIL = "PRODUCTS_LIST_FOR_CUSTOMER_FAIL";

export const PRODUCTS_LIST_FOR_ADMIN_REQUEST = "PRODUCTS_LIST_FOR_ADMIN_REQUEST";
export const PRODUCTS_LIST_FOR_ADMIN_SUCCESS = "PRODUCTS_LIST_FOR_ADMIN_SUCCESS";
export const PRODUCTS_LIST_FOR_ADMIN_FAIL = "PRODUCTS_LIST_FOR_ADMIN_FAIL";

export const PRODUCTS_CREATE_REQUEST = "PRODUCTS_CREATE_REQUEST";
export const PRODUCTS_CREATE_SUCCESS = "PRODUCTS_CREATE_SUCCESS";
export const PRODUCTS_CREATE_FAIL = "PRODUCTS_CREATE_FAIL";

export const PRODUCTS_UPDATE_BY_VENDOR_REQUEST = "PRODUCTS_UPDATE_BY_VENDOR_REQUEST";
export const PRODUCTS_UPDATE_BY_VENDOR_SUCCESS = "PRODUCTS_UPDATE_BY_VENDOR_SUCCESS";
export const PRODUCTS_UPDATE_BY_VENDOR_FAIL = "PRODUCTS_UPDATE_BY_VENDOR_FAIL";

export const PRODUCTS_DELETE_BY_VENDOR_REQUEST = "PRODUCTS_DELETE_BY_VENDOR_REQUEST";
export const PRODUCTS_DELETE_BY_VENDOR_SUCCESS = "PRODUCTS_DELETE_BY_VENDOR_SUCCESS";
export const PRODUCTS_DELETE_BY_VENDOR_FAIL = "PRODUCTS_DELETE_BY_VENDOR_FAIL";

export const PRODUCTS_UPDATE_BY_ADMIN_REQUEST = "PRODUCTS_UPDATE_BY_ADMIN_REQUEST";
export const PRODUCTS_UPDATE_BY_ADMIN_SUCCESS = "PRODUCTS_UPDATE_BY_ADMIN_SUCCESS";
export const PRODUCTS_UPDATE_BY_ADMIN_FAIL = "PRODUCTS_UPDATE_BY_ADMIN_FAIL";

export const PRODUCTS_DELETE_BY_ADMIN_REQUEST = "PRODUCTS_DELETE_BY_ADMIN_REQUEST";
export const PRODUCTS_DELETE_BY_ADMIN_SUCCESS = "PRODUCTS_DELETE_BY_ADMIN_SUCCESS";
export const PRODUCTS_DELETE_BY_ADMIN_FAIL = "PRODUCTS_DELETE_BY_ADMIN_FAIL";
